import { City } from "@/types";

export const mockCities: City[] = [
  {
    id: "1",
    name: "강남/역삼",
    region: "강남구, 서울",
    slug: "gangnam-yeoksam",
    imageUrl: "/images/gangnam.jpg",
    description: "IT 기업이 밀집한 서울의 비즈니스 중심지",
    rank: 1,
    budget: "200만원 이상",
    regionFilter: "수도권",
    environment: ["도심선호", "코워킹 필수"],
    bestSeason: ["봄", "가을"],
    reviewCount: 524,
    likeCount: 450,
    dislikeCount: 28,
    viewCount: 12453,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "홍대/연남",
    region: "마포구, 서울",
    slug: "hongdae-yeonnam",
    imageUrl: "/images/hongdae.jpg",
    description: "예술과 문화가 살아있는 힙한 동네",
    rank: 2,
    budget: "100~200만원",
    regionFilter: "수도권",
    environment: ["카페작업", "도심선호"],
    bestSeason: ["봄", "가을"],
    reviewCount: 412,
    likeCount: 380,
    dislikeCount: 15,
    viewCount: 9832,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "성수동",
    region: "성동구, 서울",
    slug: "seongsu",
    imageUrl: "/images/seongsu.jpg",
    description: "뉴욕 브루클린을 연상시키는 핫플레이스",
    rank: 3,
    budget: "100~200만원",
    regionFilter: "수도권",
    environment: ["카페작업", "도심선호"],
    bestSeason: ["봄", "가을", "겨울"],
    reviewCount: 289,
    likeCount: 250,
    dislikeCount: 22,
    viewCount: 7234,
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "판교",
    region: "성남시, 경기",
    slug: "pangyo",
    imageUrl: "/images/pangyo.jpg",
    description: "한국의 실리콘밸리, IT 기업들의 메카",
    rank: 4,
    budget: "200만원 이상",
    regionFilter: "수도권",
    environment: ["코워킹 필수", "도심선호"],
    bestSeason: ["봄", "가을"],
    reviewCount: 356,
    likeCount: 310,
    dislikeCount: 30,
    viewCount: 8456,
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "해운대",
    region: "해운대구, 부산",
    slug: "haeundae",
    imageUrl: "/images/haeundae.jpg",
    description: "바다가 보이는 워케이션의 최적지",
    rank: 5,
    budget: "100~200만원",
    regionFilter: "경상도",
    environment: ["자연친화", "카페작업"],
    bestSeason: ["여름", "가을"],
    reviewCount: 267,
    likeCount: 280,
    dislikeCount: 12,
    viewCount: 6789,
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "제주 애월",
    region: "애월읍, 제주",
    slug: "jeju-aewol",
    imageUrl: "/images/aewol.jpg",
    description: "제주 서쪽 해안의 감성적인 동네",
    rank: 6,
    budget: "100~200만원",
    regionFilter: "제주도",
    environment: ["자연친화", "카페작업"],
    bestSeason: ["봄", "여름", "가을"],
    reviewCount: 312,
    likeCount: 410,
    dislikeCount: 8,
    viewCount: 9123,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "광화문",
    region: "종로구, 서울",
    slug: "gwanghwamun",
    imageUrl: "/images/gwanghwamun.jpg",
    description: "역사와 현대가 공존하는 서울의 중심",
    rank: 7,
    budget: "200만원 이상",
    regionFilter: "수도권",
    environment: ["도심선호", "코워킹 필수"],
    bestSeason: ["봄", "가을", "겨울"],
    reviewCount: 198,
    likeCount: 190,
    dislikeCount: 25,
    viewCount: 5432,
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "송도",
    region: "연수구, 인천",
    slug: "songdo",
    imageUrl: "/images/songdo.jpg",
    description: "미래형 스마트시티, 조용하고 깔끔한 환경",
    rank: 8,
    budget: "100만원 이하",
    regionFilter: "수도권",
    environment: ["도심선호", "코워킹 필수"],
    bestSeason: ["봄", "가을", "겨울"],
    reviewCount: 167,
    likeCount: 150,
    dislikeCount: 18,
    viewCount: 4321,
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date(),
  },
  {
    id: "9",
    name: "경리단길",
    region: "용산구, 서울",
    slug: "gyeongnidan",
    imageUrl: "/images/gyeongnidan.jpg",
    description: "이태원과 한남동 사이의 힙한 골목",
    rank: 9,
    budget: "100~200만원",
    regionFilter: "수도권",
    environment: ["카페작업", "도심선호"],
    bestSeason: ["봄", "가을"],
    reviewCount: 234,
    likeCount: 220,
    dislikeCount: 20,
    viewCount: 6123,
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date(),
  },
  {
    id: "10",
    name: "광안리",
    region: "수영구, 부산",
    slug: "gwangalli",
    imageUrl: "/images/gwangalli.jpg",
    description: "광안대교가 보이는 부산의 핫플",
    rank: 10,
    budget: "100만원 이하",
    regionFilter: "경상도",
    environment: ["자연친화", "카페작업"],
    bestSeason: ["여름", "가을"],
    reviewCount: 201,
    likeCount: 170,
    dislikeCount: 14,
    viewCount: 5678,
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date(),
  },
];
